CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "Organization" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Organization" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "Bin" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Location" character varying(300),
        "QrToken" character varying(64) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Bin" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bin_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "Manager" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Manager" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Manager_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "Technician" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "EmployeeId" character varying(50) NOT NULL,
        "PinHash" character varying(300) NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Technician" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Technician_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "Part" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "BinId" integer,
        "PartName" character varying(200) NOT NULL,
        "PartNumber" character varying(100) NOT NULL,
        "CurrentStock" integer NOT NULL,
        "MinimumStock" integer NOT NULL,
        "LowStockNotificationSent" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Part" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Part_Bin_BinId" FOREIGN KEY ("BinId") REFERENCES "Bin" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Part_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_Manager_UserId" FOREIGN KEY ("UserId") REFERENCES "Manager" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_Manager_UserId" FOREIGN KEY ("UserId") REFERENCES "Manager" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_Manager_UserId" FOREIGN KEY ("UserId") REFERENCES "Manager" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE TABLE "StockTransaction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "PartId" integer NOT NULL,
        "BinId" integer NOT NULL,
        "ActorType" integer NOT NULL,
        "ActorId" integer NOT NULL,
        "ActorName" character varying(200) NOT NULL,
        "QuantityDelta" integer NOT NULL,
        "PreviousStock" integer NOT NULL,
        "NewStock" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_StockTransaction" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockTransaction_Bin_BinId" FOREIGN KEY ("BinId") REFERENCES "Bin" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockTransaction_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StockTransaction_Part_PartId" FOREIGN KEY ("PartId") REFERENCES "Part" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "IX_Bin_OrganizationId_Code" ON "Bin" ("OrganizationId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "IX_Bin_QrToken" ON "Bin" ("QrToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "EmailIndex" ON "Manager" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_Manager_OrganizationId" ON "Manager" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Manager" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "IX_Part_BinId" ON "Part" ("BinId") WHERE "BinId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "IX_Part_OrganizationId_PartNumber" ON "Part" ("OrganizationId", "PartNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_StockTransaction_BinId" ON "StockTransaction" ("BinId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_StockTransaction_CreatedAt" ON "StockTransaction" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_StockTransaction_OrganizationId" ON "StockTransaction" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE INDEX "IX_StockTransaction_PartId" ON "StockTransaction" ("PartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    CREATE UNIQUE INDEX "IX_Technician_OrganizationId_EmployeeId" ON "Technician" ("OrganizationId", "EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814054243_Initial_Script') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260814054243_Initial_Script', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP TABLE "AspNetUserClaims";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP TABLE "AspNetUserLogins";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP TABLE "AspNetUserTokens";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP TABLE "Technician";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP INDEX "EmailIndex";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    DROP INDEX "UserNameIndex";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "StockTransaction" DROP COLUMN "ActorId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "StockTransaction" DROP COLUMN "ActorName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "StockTransaction" DROP COLUMN "ActorType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "AccessFailedCount";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "ConcurrencyStamp";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "EmailConfirmed";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "LockoutEnabled";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "LockoutEnd";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "NormalizedEmail";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "NormalizedUserName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "PhoneNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "PhoneNumberConfirmed";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "SecurityStamp";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "TwoFactorEnabled";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    ALTER TABLE "Manager" DROP COLUMN "UserName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    UPDATE "Manager" SET "PasswordHash" = '' WHERE "PasswordHash" IS NULL;
    ALTER TABLE "Manager" ALTER COLUMN "PasswordHash" SET NOT NULL;
    ALTER TABLE "Manager" ALTER COLUMN "PasswordHash" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    UPDATE "Manager" SET "Email" = '' WHERE "Email" IS NULL;
    ALTER TABLE "Manager" ALTER COLUMN "Email" SET NOT NULL;
    ALTER TABLE "Manager" ALTER COLUMN "Email" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    CREATE UNIQUE INDEX "IX_Manager_Email" ON "Manager" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814122103_Remove_Identity_And_Actor_Tracking') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260814122103_Remove_Identity_And_Actor_Tracking', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814123722_Make_PartNumber_Optional') THEN
    ALTER TABLE "Part" ALTER COLUMN "PartNumber" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260814123722_Make_PartNumber_Optional') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260814123722_Make_PartNumber_Optional', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE TABLE "Bill" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "CustomerName" character varying(200),
        "CustomerPhone" character varying(30),
        "Total" numeric(12,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Bill" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bill_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE TABLE "Product" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Code" character varying(100),
        "Unit" character varying(20) NOT NULL,
        "SellingPrice" numeric(12,2) NOT NULL,
        "CurrentStock" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Product" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Product_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE TABLE "BillItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BillId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "ProductName" character varying(200) NOT NULL,
        "UnitPrice" numeric(12,2) NOT NULL,
        "Quantity" integer NOT NULL,
        "LineTotal" numeric(12,2) NOT NULL,
        CONSTRAINT "PK_BillItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BillItem_Bill_BillId" FOREIGN KEY ("BillId") REFERENCES "Bill" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_BillItem_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE TABLE "StockMovement" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Reason" character varying(20) NOT NULL,
        "QuantityDelta" integer NOT NULL,
        "PreviousStock" integer NOT NULL,
        "NewStock" integer NOT NULL,
        "BillId" integer,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_StockMovement" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockMovement_Bill_BillId" FOREIGN KEY ("BillId") REFERENCES "Bill" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockMovement_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StockMovement_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_Bill_CreatedAt" ON "Bill" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_Bill_OrganizationId" ON "Bill" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_BillItem_BillId" ON "BillItem" ("BillId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_BillItem_ProductId" ON "BillItem" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE UNIQUE INDEX "IX_Product_OrganizationId_Code" ON "Product" ("OrganizationId", "Code") WHERE "Code" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_Product_OrganizationId_Name" ON "Product" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_StockMovement_BillId" ON "StockMovement" ("BillId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_StockMovement_CreatedAt" ON "StockMovement" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_StockMovement_OrganizationId" ON "StockMovement" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    CREATE INDEX "IX_StockMovement_ProductId_CreatedAt" ON "StockMovement" ("ProductId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828161049_Add_Billing_And_Products') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828161049_Add_Billing_And_Products', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828162940_Add_Product_Hsn_Gst_Active') THEN
    ALTER TABLE "Product" ADD "GstRate" numeric(5,2) NOT NULL DEFAULT 18.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828162940_Add_Product_Hsn_Gst_Active') THEN
    ALTER TABLE "Product" ADD "HsnCode" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828162940_Add_Product_Hsn_Gst_Active') THEN
    ALTER TABLE "Product" ADD "IsActive" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828162940_Add_Product_Hsn_Gst_Active') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828162940_Add_Product_Hsn_Gst_Active', '10.0.11');
    END IF;
END $EF$;
COMMIT;

